[package]
name = "sovd"
description = "SOVD (ISO 17978) models and types"
readme = "README.md"
edition = { workspace = true }
license = { workspace = true }
version = { workspace = true }

[dependencies]
serde = { workspace = true }
