[package]
name = "opensovd-cli"
description = "Cli tools for opensovd"
readme = "README.md"
build = "build.rs"

edition = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
license = { workspace = true }
version = { workspace = true }
authors = { workspace = true }

[features]
default = ["tracing"]
tracing = ["opensovd-tracing/tracing", "dep:tracing", "dep:tracing-subscriber"]
ui = ["opensovd-server/ui"]

[[bin]]
name = "osovd-gateway"
path = "gateway/src/main.rs"

[[bin]]
name = "osovd-cli"
path = "cli/src/main.rs"

[dependencies]
clap = { workspace = true }
opensovd-server = { workspace = true }
opensovd-tracing = { workspace = true }
sovd = { workspace = true }
tokio = { workspace = true }
openssl = { workspace = true, optional = true }
tracing = { workspace = true, optional = true }
tracing-subscriber = { workspace = true, optional = true, features = [
    "smallvec",
] }
